# Generated by Django 3.2 on 2022-08-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductImages',
        ),
    ]
